name: Bug Report
description: Report a bug in Guardian Wallet
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `gw send ...`
        2. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - guardian-server
        - guardian-app (dashboard)
        - guardian-cli
        - guardian-signer (SDK)
        - guardian-schemes
        - guardian-chains
        - guardian-core
        - guardian-mpc-wasm
        - guardian-auth
        - Other
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - Node.js version
        - pnpm version
        - OS
        - Deployment: Docker / local dev
        - KMS provider: vault-kv / local-file (if relevant)
        - Network (if relevant): base-sepolia / mainnet / etc.
